version: "3.7"
services:

  # stager task database
  db:
    image: redis
    user: root
    volumes:
      - ${TASK_DB_REDIS_DATA:-db}:/data
    command: --appendonly yes

  # stager api server
  api-server:
    build:
      context: .
      target: api-server
    image: ${DOCKER_REGISTRY:-dccn}/data-stager-api:${DOCKER_IMAGE_TAG:-latest}
    user: root
    ports:
      - ${API_EXTERNAL_PORT:-8080}:8080
    volumes:
      - ${API_CONFIG:-./config/api-server.yml}:/etc/stager/api-server.yml:ro
    depends_on:
      - db
    command: -p 8080 -r redis://db:6379 -c /etc/stager/api-server.yml
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # stager worker
  worker:
    build:
      context: .
      target: worker
    image: ${DOCKER_REGISTRY:-dccn}/data-stager-worker:${DOCKER_IMAGE_TAG:-latest}
    user: root
    volumes:
      - ${IRODS_ICAT_CERT:-./docker/worker/icat.pem}:/opt/irods/ssl/icat.pem:ro
      - ${WORKER_CONFIG:-./config/worker.yml}:/etc/stager/worker.yml:ro
      - ${CRYPTO_RSA_PRIVATE}:/etc/stager/ssl/keypair.pem:ro
    depends_on:
      - api-server
    command: -r redis://db:6379 -c /etc/stager/worker.yml
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # web ui for end user
  ui:
    build:
      context: ./ui
    image: ${DOCKER_REGISTRY:-dccn}/data-stager-ui:${DOCKER_IMAGE_TAG:-latest}
    user: root
    environment:
      - AUTH_SERVER=${AUTH_SERVER:-https://authserver}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID:-clientid}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET:-clientsecret}
    volumes:
      - ${UI_CONFIG:-./ui/config/default.json}:/opt/stager-ui/config/default.json
      - ${CRYPTO_RSA_PUBLIC}:/opt/stager-ui/ssl/public.pem:ro
    ports:
      - ${UI_EXTERNAL_PORT:-3080}:3080
    depends_on:
      - api-server
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"      

  # web ui for task administration
  admin:
    image: hibiken/asynqmon:${ASYNQMON_IMAGE_TAG:-latest}
    command: --port 3081 --redis-url redis://db:6379
    ports:
      - ${ASYNQMON_EXTERNAL_PORT:-3081}:3081
    depends_on:
      - db
      - api-server
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

volumes:
  db:
    
