version: "3.7"
services:
  db:
    image: redis
    user: root
    volumes:
      - ${TASK_DB_REDIS_DATA:-stager_db_data}:/data
    command: --appendonly yes

  api-server:
    build:
      context: .
      target: api-server
    image: ${DOCKER_REGISTRY:-dccn}/data-stager-api:${DOCKER_IMAGE_TAG:-latest}
    user: root
    ports:
      - ${API_EXTERNAL_PORT:-8080}:8080
    volumes:
      - ${API_CONFIG:-./config/api-server.yml}:/etc/stager/api-server.yml:ro
    depends_on:
      - db
    command: -v -p 8080 -r redis://db:6379 -c /etc/stager/api-server.yml
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  worker:
    build:
      context: .
      target: worker
    image: ${DOCKER_REGISTRY:-dccn}/data-stager-worker:${DOCKER_IMAGE_TAG:-latest}
    user: root
    volumes:
      - ${IRODS_ICAT_CERT:-./docker/worker/icat.pem}:/opt/irods/ssl/icat.pem:ro
      - ${WORKER_CONFIG:-./config/worker.yml}:/etc/stager/worker.yml:ro
    depends_on:
      - api-server
    command: -v -r redis://db:6379 -c /etc/stager/worker.yml
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  webui:
    image: hibiken/asynqmon:${ASYNQMON_IMAGE_TAG:-latest}
    command: --port 8081 --redis-url redis://db:6379
    ports:
      - ${ASYNQMON_EXTERNAL_PORT:-8081}:8081
    depends_on:
      - db
      - api-server
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

volumes:
  stager_db_data:
    