version: "3.7"
services:
  db:
    image: redis
    user: root
    command: --appendonly yes

  api-server:
    build:
      context: .
      target: api-server
    image: ${DOCKER_REGISTRY:-dccn}/data-stager-api:${DOCKER_IMAGE_TAG:-latest}
    user: root
    ports:
      - ${API_EXTERNAL_PORT:-8080}:8080
    volumes:
      - ${API_CONFIG:-/mnt/docker/scripts/microservices/data-stager/api-server.yml}:/etc/data-stager/config.yml:ro
    depends_on:
      - db
    command: -p 8080 -r redis://db:6379 -c /etc/data-stager/config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  worker:
    build:
      context: .
      target: worker
    image: ${DOCKER_REGISTRY:-dccn}/data-stager-worker:${DOCKER_IMAGE_TAG:-latest}
    user: root
    environment:
      - IRODS_HOST
      - IRODS_PORT
      - IRODS_ZONE_NAME
      - IRODS_USER_NAME
    volumes:
      - ${IRODS_ICAT_CERT:-/mnt/docker/scripts/microservices/data-stager/icat.pem}:/opt/irods/ssl/icat.pem
      - ${WORKER_CONFIG:-/mnt/docker/scripts/microservices/data-stager/worker.yml}:/etc/data-stager/config.yml:ro
    depends_on:
      - api-server
    command: -r redis://db:6379 -c /etc/data-stager/config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  webui:
    image: hibiken/asynqmon:${ASYNQMON_IMAGE_TAG:-latest}
    command: --port 8081 --redis-url redis://db:6379
    ports:
      - ${ASYNQMON_EXTERNAL_PORT:-8081}:8081
    depends_on:
      - db
      - api-server
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"