version: "3.7"
services:
  api-server:
    volumes:
      - ${PROJECT_VOL:-/project}:/project
      - ${PROJECT_FREENAS_VOL:-/project_freenas}:/project_freenas
      - ${PROJECT_CEPHFS_VOL:-/project_cephfs}:/project_cephfs
  worker:
    volumes:
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
      - ${PROJECT_VOL:-/project}:/project
      - ${PROJECT_FREENAS_VOL:-/project_freenas}:/project_freenas
      - ${PROJECT_CEPHFS_VOL:-/project_cephfs}:/project_cephfs
    deploy:
      placement:
        constraints:
          - node.labels.IpRange==44
  ui:
    networks:
      default:
      proxynet:
        aliases:
          - dr-data-stager-ui
  admin:
    networks:
      default:
      proxynet:
        aliases:
          - dr-data-stager-admin

networks:
  default:
    name: dr-data-stager-net
    attachable: true
  proxynet:
    external: true