// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/client/models"
)

// GetJobsStatusReader is a Reader for the GetJobsStatus structure.
type GetJobsStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetJobsStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetJobsStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetJobsStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /jobs/{status}] GetJobsStatus", response, response.Code())
	}
}

// NewGetJobsStatusOK creates a GetJobsStatusOK with default headers values
func NewGetJobsStatusOK() *GetJobsStatusOK {
	return &GetJobsStatusOK{}
}

/*
GetJobsStatusOK describes a response with status code 200, with default header values.

success
*/
type GetJobsStatusOK struct {
	Payload *models.ResponseBodyJobs
}

// IsSuccess returns true when this get jobs status o k response has a 2xx status code
func (o *GetJobsStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get jobs status o k response has a 3xx status code
func (o *GetJobsStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get jobs status o k response has a 4xx status code
func (o *GetJobsStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get jobs status o k response has a 5xx status code
func (o *GetJobsStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get jobs status o k response a status code equal to that given
func (o *GetJobsStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get jobs status o k response
func (o *GetJobsStatusOK) Code() int {
	return 200
}

func (o *GetJobsStatusOK) Error() string {
	return fmt.Sprintf("[GET /jobs/{status}][%d] getJobsStatusOK  %+v", 200, o.Payload)
}

func (o *GetJobsStatusOK) String() string {
	return fmt.Sprintf("[GET /jobs/{status}][%d] getJobsStatusOK  %+v", 200, o.Payload)
}

func (o *GetJobsStatusOK) GetPayload() *models.ResponseBodyJobs {
	return o.Payload
}

func (o *GetJobsStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyJobs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobsStatusInternalServerError creates a GetJobsStatusInternalServerError with default headers values
func NewGetJobsStatusInternalServerError() *GetJobsStatusInternalServerError {
	return &GetJobsStatusInternalServerError{}
}

/*
GetJobsStatusInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetJobsStatusInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get jobs status internal server error response has a 2xx status code
func (o *GetJobsStatusInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get jobs status internal server error response has a 3xx status code
func (o *GetJobsStatusInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get jobs status internal server error response has a 4xx status code
func (o *GetJobsStatusInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get jobs status internal server error response has a 5xx status code
func (o *GetJobsStatusInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get jobs status internal server error response a status code equal to that given
func (o *GetJobsStatusInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get jobs status internal server error response
func (o *GetJobsStatusInternalServerError) Code() int {
	return 500
}

func (o *GetJobsStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /jobs/{status}][%d] getJobsStatusInternalServerError  %+v", 500, o.Payload)
}

func (o *GetJobsStatusInternalServerError) String() string {
	return fmt.Sprintf("[GET /jobs/{status}][%d] getJobsStatusInternalServerError  %+v", 500, o.Payload)
}

func (o *GetJobsStatusInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetJobsStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
