// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/client/models"
)

// GetJobIDReader is a Reader for the GetJobID structure.
type GetJobIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetJobIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetJobIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetJobIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetJobIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetJobIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /job/{id}] GetJobID", response, response.Code())
	}
}

// NewGetJobIDOK creates a GetJobIDOK with default headers values
func NewGetJobIDOK() *GetJobIDOK {
	return &GetJobIDOK{}
}

/*
GetJobIDOK describes a response with status code 200, with default header values.

success
*/
type GetJobIDOK struct {
	Payload *models.JobInfo
}

// IsSuccess returns true when this get job Id o k response has a 2xx status code
func (o *GetJobIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get job Id o k response has a 3xx status code
func (o *GetJobIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get job Id o k response has a 4xx status code
func (o *GetJobIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get job Id o k response has a 5xx status code
func (o *GetJobIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get job Id o k response a status code equal to that given
func (o *GetJobIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get job Id o k response
func (o *GetJobIDOK) Code() int {
	return 200
}

func (o *GetJobIDOK) Error() string {
	return fmt.Sprintf("[GET /job/{id}][%d] getJobIdOK  %+v", 200, o.Payload)
}

func (o *GetJobIDOK) String() string {
	return fmt.Sprintf("[GET /job/{id}][%d] getJobIdOK  %+v", 200, o.Payload)
}

func (o *GetJobIDOK) GetPayload() *models.JobInfo {
	return o.Payload
}

func (o *GetJobIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobIDBadRequest creates a GetJobIDBadRequest with default headers values
func NewGetJobIDBadRequest() *GetJobIDBadRequest {
	return &GetJobIDBadRequest{}
}

/*
GetJobIDBadRequest describes a response with status code 400, with default header values.

bad request
*/
type GetJobIDBadRequest struct {
	Payload *models.ResponseBody400
}

// IsSuccess returns true when this get job Id bad request response has a 2xx status code
func (o *GetJobIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get job Id bad request response has a 3xx status code
func (o *GetJobIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get job Id bad request response has a 4xx status code
func (o *GetJobIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get job Id bad request response has a 5xx status code
func (o *GetJobIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get job Id bad request response a status code equal to that given
func (o *GetJobIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get job Id bad request response
func (o *GetJobIDBadRequest) Code() int {
	return 400
}

func (o *GetJobIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /job/{id}][%d] getJobIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetJobIDBadRequest) String() string {
	return fmt.Sprintf("[GET /job/{id}][%d] getJobIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetJobIDBadRequest) GetPayload() *models.ResponseBody400 {
	return o.Payload
}

func (o *GetJobIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobIDNotFound creates a GetJobIDNotFound with default headers values
func NewGetJobIDNotFound() *GetJobIDNotFound {
	return &GetJobIDNotFound{}
}

/*
GetJobIDNotFound describes a response with status code 404, with default header values.

job not found
*/
type GetJobIDNotFound struct {
	Payload string
}

// IsSuccess returns true when this get job Id not found response has a 2xx status code
func (o *GetJobIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get job Id not found response has a 3xx status code
func (o *GetJobIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get job Id not found response has a 4xx status code
func (o *GetJobIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get job Id not found response has a 5xx status code
func (o *GetJobIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get job Id not found response a status code equal to that given
func (o *GetJobIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get job Id not found response
func (o *GetJobIDNotFound) Code() int {
	return 404
}

func (o *GetJobIDNotFound) Error() string {
	return fmt.Sprintf("[GET /job/{id}][%d] getJobIdNotFound  %+v", 404, o.Payload)
}

func (o *GetJobIDNotFound) String() string {
	return fmt.Sprintf("[GET /job/{id}][%d] getJobIdNotFound  %+v", 404, o.Payload)
}

func (o *GetJobIDNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetJobIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobIDInternalServerError creates a GetJobIDInternalServerError with default headers values
func NewGetJobIDInternalServerError() *GetJobIDInternalServerError {
	return &GetJobIDInternalServerError{}
}

/*
GetJobIDInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetJobIDInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get job Id internal server error response has a 2xx status code
func (o *GetJobIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get job Id internal server error response has a 3xx status code
func (o *GetJobIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get job Id internal server error response has a 4xx status code
func (o *GetJobIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get job Id internal server error response has a 5xx status code
func (o *GetJobIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get job Id internal server error response a status code equal to that given
func (o *GetJobIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get job Id internal server error response
func (o *GetJobIDInternalServerError) Code() int {
	return 500
}

func (o *GetJobIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /job/{id}][%d] getJobIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetJobIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /job/{id}][%d] getJobIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetJobIDInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetJobIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
