// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetJobsStatusParams creates a new GetJobsStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetJobsStatusParams() *GetJobsStatusParams {
	return &GetJobsStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetJobsStatusParamsWithTimeout creates a new GetJobsStatusParams object
// with the ability to set a timeout on a request.
func NewGetJobsStatusParamsWithTimeout(timeout time.Duration) *GetJobsStatusParams {
	return &GetJobsStatusParams{
		timeout: timeout,
	}
}

// NewGetJobsStatusParamsWithContext creates a new GetJobsStatusParams object
// with the ability to set a context for a request.
func NewGetJobsStatusParamsWithContext(ctx context.Context) *GetJobsStatusParams {
	return &GetJobsStatusParams{
		Context: ctx,
	}
}

// NewGetJobsStatusParamsWithHTTPClient creates a new GetJobsStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetJobsStatusParamsWithHTTPClient(client *http.Client) *GetJobsStatusParams {
	return &GetJobsStatusParams{
		HTTPClient: client,
	}
}

/*
GetJobsStatusParams contains all the parameters to send to the API endpoint

	for the get jobs status operation.

	Typically these are written to a http.Request.
*/
type GetJobsStatusParams struct {

	/* Status.

	   job status
	*/
	Status string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get jobs status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJobsStatusParams) WithDefaults() *GetJobsStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get jobs status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJobsStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get jobs status params
func (o *GetJobsStatusParams) WithTimeout(timeout time.Duration) *GetJobsStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get jobs status params
func (o *GetJobsStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get jobs status params
func (o *GetJobsStatusParams) WithContext(ctx context.Context) *GetJobsStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get jobs status params
func (o *GetJobsStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get jobs status params
func (o *GetJobsStatusParams) WithHTTPClient(client *http.Client) *GetJobsStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get jobs status params
func (o *GetJobsStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStatus adds the status to the get jobs status params
func (o *GetJobsStatusParams) WithStatus(status string) *GetJobsStatusParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the get jobs status params
func (o *GetJobsStatusParams) SetStatus(status string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *GetJobsStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param status
	if err := r.SetPathParam("status", o.Status); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
