// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/client/models"
)

// GetDirReader is a Reader for the GetDir structure.
type GetDirReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDirReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDirOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetDirInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /dir] GetDir", response, response.Code())
	}
}

// NewGetDirOK creates a GetDirOK with default headers values
func NewGetDirOK() *GetDirOK {
	return &GetDirOK{}
}

/*
GetDirOK describes a response with status code 200, with default header values.

success
*/
type GetDirOK struct {
	Payload *models.ResponseDirEntries
}

// IsSuccess returns true when this get dir o k response has a 2xx status code
func (o *GetDirOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get dir o k response has a 3xx status code
func (o *GetDirOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get dir o k response has a 4xx status code
func (o *GetDirOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get dir o k response has a 5xx status code
func (o *GetDirOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get dir o k response a status code equal to that given
func (o *GetDirOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get dir o k response
func (o *GetDirOK) Code() int {
	return 200
}

func (o *GetDirOK) Error() string {
	return fmt.Sprintf("[GET /dir][%d] getDirOK  %+v", 200, o.Payload)
}

func (o *GetDirOK) String() string {
	return fmt.Sprintf("[GET /dir][%d] getDirOK  %+v", 200, o.Payload)
}

func (o *GetDirOK) GetPayload() *models.ResponseDirEntries {
	return o.Payload
}

func (o *GetDirOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseDirEntries)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDirInternalServerError creates a GetDirInternalServerError with default headers values
func NewGetDirInternalServerError() *GetDirInternalServerError {
	return &GetDirInternalServerError{}
}

/*
GetDirInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetDirInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get dir internal server error response has a 2xx status code
func (o *GetDirInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get dir internal server error response has a 3xx status code
func (o *GetDirInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get dir internal server error response has a 4xx status code
func (o *GetDirInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get dir internal server error response has a 5xx status code
func (o *GetDirInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get dir internal server error response a status code equal to that given
func (o *GetDirInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get dir internal server error response
func (o *GetDirInternalServerError) Code() int {
	return 500
}

func (o *GetDirInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dir][%d] getDirInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDirInternalServerError) String() string {
	return fmt.Sprintf("[GET /dir][%d] getDirInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDirInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetDirInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
