// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetJobIDParams creates a new GetJobIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetJobIDParams() *GetJobIDParams {
	return &GetJobIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetJobIDParamsWithTimeout creates a new GetJobIDParams object
// with the ability to set a timeout on a request.
func NewGetJobIDParamsWithTimeout(timeout time.Duration) *GetJobIDParams {
	return &GetJobIDParams{
		timeout: timeout,
	}
}

// NewGetJobIDParamsWithContext creates a new GetJobIDParams object
// with the ability to set a context for a request.
func NewGetJobIDParamsWithContext(ctx context.Context) *GetJobIDParams {
	return &GetJobIDParams{
		Context: ctx,
	}
}

// NewGetJobIDParamsWithHTTPClient creates a new GetJobIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetJobIDParamsWithHTTPClient(client *http.Client) *GetJobIDParams {
	return &GetJobIDParams{
		HTTPClient: client,
	}
}

/*
GetJobIDParams contains all the parameters to send to the API endpoint

	for the get job ID operation.

	Typically these are written to a http.Request.
*/
type GetJobIDParams struct {

	/* ID.

	   job identifier
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get job ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJobIDParams) WithDefaults() *GetJobIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get job ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJobIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get job ID params
func (o *GetJobIDParams) WithTimeout(timeout time.Duration) *GetJobIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get job ID params
func (o *GetJobIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get job ID params
func (o *GetJobIDParams) WithContext(ctx context.Context) *GetJobIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get job ID params
func (o *GetJobIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get job ID params
func (o *GetJobIDParams) WithHTTPClient(client *http.Client) *GetJobIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get job ID params
func (o *GetJobIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get job ID params
func (o *GetJobIDParams) WithID(id string) *GetJobIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get job ID params
func (o *GetJobIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetJobIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
