// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/client/models"
)

// GetDacProjectNumberReader is a Reader for the GetDacProjectNumber structure.
type GetDacProjectNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDacProjectNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDacProjectNumberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDacProjectNumberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDacProjectNumberInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /dac/project/{number}] GetDacProjectNumber", response, response.Code())
	}
}

// NewGetDacProjectNumberOK creates a GetDacProjectNumberOK with default headers values
func NewGetDacProjectNumberOK() *GetDacProjectNumberOK {
	return &GetDacProjectNumberOK{}
}

/*
GetDacProjectNumberOK describes a response with status code 200, with default header values.

success
*/
type GetDacProjectNumberOK struct {
	Payload *models.Collection
}

// IsSuccess returns true when this get dac project number o k response has a 2xx status code
func (o *GetDacProjectNumberOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get dac project number o k response has a 3xx status code
func (o *GetDacProjectNumberOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get dac project number o k response has a 4xx status code
func (o *GetDacProjectNumberOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get dac project number o k response has a 5xx status code
func (o *GetDacProjectNumberOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get dac project number o k response a status code equal to that given
func (o *GetDacProjectNumberOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get dac project number o k response
func (o *GetDacProjectNumberOK) Code() int {
	return 200
}

func (o *GetDacProjectNumberOK) Error() string {
	return fmt.Sprintf("[GET /dac/project/{number}][%d] getDacProjectNumberOK  %+v", 200, o.Payload)
}

func (o *GetDacProjectNumberOK) String() string {
	return fmt.Sprintf("[GET /dac/project/{number}][%d] getDacProjectNumberOK  %+v", 200, o.Payload)
}

func (o *GetDacProjectNumberOK) GetPayload() *models.Collection {
	return o.Payload
}

func (o *GetDacProjectNumberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Collection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDacProjectNumberNotFound creates a GetDacProjectNumberNotFound with default headers values
func NewGetDacProjectNumberNotFound() *GetDacProjectNumberNotFound {
	return &GetDacProjectNumberNotFound{}
}

/*
GetDacProjectNumberNotFound describes a response with status code 404, with default header values.

collection not found
*/
type GetDacProjectNumberNotFound struct {
	Payload string
}

// IsSuccess returns true when this get dac project number not found response has a 2xx status code
func (o *GetDacProjectNumberNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get dac project number not found response has a 3xx status code
func (o *GetDacProjectNumberNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get dac project number not found response has a 4xx status code
func (o *GetDacProjectNumberNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get dac project number not found response has a 5xx status code
func (o *GetDacProjectNumberNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get dac project number not found response a status code equal to that given
func (o *GetDacProjectNumberNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get dac project number not found response
func (o *GetDacProjectNumberNotFound) Code() int {
	return 404
}

func (o *GetDacProjectNumberNotFound) Error() string {
	return fmt.Sprintf("[GET /dac/project/{number}][%d] getDacProjectNumberNotFound  %+v", 404, o.Payload)
}

func (o *GetDacProjectNumberNotFound) String() string {
	return fmt.Sprintf("[GET /dac/project/{number}][%d] getDacProjectNumberNotFound  %+v", 404, o.Payload)
}

func (o *GetDacProjectNumberNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetDacProjectNumberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDacProjectNumberInternalServerError creates a GetDacProjectNumberInternalServerError with default headers values
func NewGetDacProjectNumberInternalServerError() *GetDacProjectNumberInternalServerError {
	return &GetDacProjectNumberInternalServerError{}
}

/*
GetDacProjectNumberInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetDacProjectNumberInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get dac project number internal server error response has a 2xx status code
func (o *GetDacProjectNumberInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get dac project number internal server error response has a 3xx status code
func (o *GetDacProjectNumberInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get dac project number internal server error response has a 4xx status code
func (o *GetDacProjectNumberInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get dac project number internal server error response has a 5xx status code
func (o *GetDacProjectNumberInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get dac project number internal server error response a status code equal to that given
func (o *GetDacProjectNumberInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get dac project number internal server error response
func (o *GetDacProjectNumberInternalServerError) Code() int {
	return 500
}

func (o *GetDacProjectNumberInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dac/project/{number}][%d] getDacProjectNumberInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDacProjectNumberInternalServerError) String() string {
	return fmt.Sprintf("[GET /dac/project/{number}][%d] getDacProjectNumberInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDacProjectNumberInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetDacProjectNumberInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
