// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRdmTypeProjectNumberParams creates a new GetRdmTypeProjectNumberParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRdmTypeProjectNumberParams() *GetRdmTypeProjectNumberParams {
	return &GetRdmTypeProjectNumberParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRdmTypeProjectNumberParamsWithTimeout creates a new GetRdmTypeProjectNumberParams object
// with the ability to set a timeout on a request.
func NewGetRdmTypeProjectNumberParamsWithTimeout(timeout time.Duration) *GetRdmTypeProjectNumberParams {
	return &GetRdmTypeProjectNumberParams{
		timeout: timeout,
	}
}

// NewGetRdmTypeProjectNumberParamsWithContext creates a new GetRdmTypeProjectNumberParams object
// with the ability to set a context for a request.
func NewGetRdmTypeProjectNumberParamsWithContext(ctx context.Context) *GetRdmTypeProjectNumberParams {
	return &GetRdmTypeProjectNumberParams{
		Context: ctx,
	}
}

// NewGetRdmTypeProjectNumberParamsWithHTTPClient creates a new GetRdmTypeProjectNumberParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRdmTypeProjectNumberParamsWithHTTPClient(client *http.Client) *GetRdmTypeProjectNumberParams {
	return &GetRdmTypeProjectNumberParams{
		HTTPClient: client,
	}
}

/*
GetRdmTypeProjectNumberParams contains all the parameters to send to the API endpoint

	for the get rdm type project number operation.

	Typically these are written to a http.Request.
*/
type GetRdmTypeProjectNumberParams struct {

	/* Number.

	   project number
	*/
	Number string

	/* Type.

	   type of collection
	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get rdm type project number params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRdmTypeProjectNumberParams) WithDefaults() *GetRdmTypeProjectNumberParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get rdm type project number params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRdmTypeProjectNumberParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) WithTimeout(timeout time.Duration) *GetRdmTypeProjectNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) WithContext(ctx context.Context) *GetRdmTypeProjectNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) WithHTTPClient(client *http.Client) *GetRdmTypeProjectNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNumber adds the number to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) WithNumber(number string) *GetRdmTypeProjectNumberParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) SetNumber(number string) {
	o.Number = number
}

// WithType adds the typeVar to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) WithType(typeVar string) *GetRdmTypeProjectNumberParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get rdm type project number params
func (o *GetRdmTypeProjectNumberParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetRdmTypeProjectNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param number
	if err := r.SetPathParam("number", o.Number); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
