// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/client/models"
)

// GetJobsStatusReader is a Reader for the GetJobsStatus structure.
type GetJobsStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetJobsStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetJobsStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetJobsStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetJobsStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetJobsStatusOK creates a GetJobsStatusOK with default headers values
func NewGetJobsStatusOK() *GetJobsStatusOK {
	return &GetJobsStatusOK{}
}

/* GetJobsStatusOK describes a response with status code 200, with default header values.

success
*/
type GetJobsStatusOK struct {
	Payload *models.ResponseBodyJobs
}

func (o *GetJobsStatusOK) Error() string {
	return fmt.Sprintf("[GET /jobs/{status}][%d] getJobsStatusOK  %+v", 200, o.Payload)
}
func (o *GetJobsStatusOK) GetPayload() *models.ResponseBodyJobs {
	return o.Payload
}

func (o *GetJobsStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyJobs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobsStatusBadRequest creates a GetJobsStatusBadRequest with default headers values
func NewGetJobsStatusBadRequest() *GetJobsStatusBadRequest {
	return &GetJobsStatusBadRequest{}
}

/* GetJobsStatusBadRequest describes a response with status code 400, with default header values.

bad request
*/
type GetJobsStatusBadRequest struct {
	Payload *models.ResponseBody400
}

func (o *GetJobsStatusBadRequest) Error() string {
	return fmt.Sprintf("[GET /jobs/{status}][%d] getJobsStatusBadRequest  %+v", 400, o.Payload)
}
func (o *GetJobsStatusBadRequest) GetPayload() *models.ResponseBody400 {
	return o.Payload
}

func (o *GetJobsStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobsStatusInternalServerError creates a GetJobsStatusInternalServerError with default headers values
func NewGetJobsStatusInternalServerError() *GetJobsStatusInternalServerError {
	return &GetJobsStatusInternalServerError{}
}

/* GetJobsStatusInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetJobsStatusInternalServerError struct {
	Payload *models.ResponseBody500
}

func (o *GetJobsStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /jobs/{status}][%d] getJobsStatusInternalServerError  %+v", 500, o.Payload)
}
func (o *GetJobsStatusInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetJobsStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
