// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDacProjectNumberParams creates a new GetDacProjectNumberParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDacProjectNumberParams() *GetDacProjectNumberParams {
	return &GetDacProjectNumberParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDacProjectNumberParamsWithTimeout creates a new GetDacProjectNumberParams object
// with the ability to set a timeout on a request.
func NewGetDacProjectNumberParamsWithTimeout(timeout time.Duration) *GetDacProjectNumberParams {
	return &GetDacProjectNumberParams{
		timeout: timeout,
	}
}

// NewGetDacProjectNumberParamsWithContext creates a new GetDacProjectNumberParams object
// with the ability to set a context for a request.
func NewGetDacProjectNumberParamsWithContext(ctx context.Context) *GetDacProjectNumberParams {
	return &GetDacProjectNumberParams{
		Context: ctx,
	}
}

// NewGetDacProjectNumberParamsWithHTTPClient creates a new GetDacProjectNumberParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDacProjectNumberParamsWithHTTPClient(client *http.Client) *GetDacProjectNumberParams {
	return &GetDacProjectNumberParams{
		HTTPClient: client,
	}
}

/*
GetDacProjectNumberParams contains all the parameters to send to the API endpoint

	for the get dac project number operation.

	Typically these are written to a http.Request.
*/
type GetDacProjectNumberParams struct {

	/* Number.

	   project number
	*/
	Number string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dac project number params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDacProjectNumberParams) WithDefaults() *GetDacProjectNumberParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dac project number params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDacProjectNumberParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get dac project number params
func (o *GetDacProjectNumberParams) WithTimeout(timeout time.Duration) *GetDacProjectNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dac project number params
func (o *GetDacProjectNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dac project number params
func (o *GetDacProjectNumberParams) WithContext(ctx context.Context) *GetDacProjectNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dac project number params
func (o *GetDacProjectNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dac project number params
func (o *GetDacProjectNumberParams) WithHTTPClient(client *http.Client) *GetDacProjectNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dac project number params
func (o *GetDacProjectNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNumber adds the number to the get dac project number params
func (o *GetDacProjectNumberParams) WithNumber(number string) *GetDacProjectNumberParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the get dac project number params
func (o *GetDacProjectNumberParams) SetNumber(number string) {
	o.Number = number
}

// WriteToRequest writes these params to a swagger request
func (o *GetDacProjectNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param number
	if err := r.SetPathParam("number", o.Number); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
