// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCollectionTypeProjectNumberParams creates a new GetCollectionTypeProjectNumberParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollectionTypeProjectNumberParams() *GetCollectionTypeProjectNumberParams {
	return &GetCollectionTypeProjectNumberParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionTypeProjectNumberParamsWithTimeout creates a new GetCollectionTypeProjectNumberParams object
// with the ability to set a timeout on a request.
func NewGetCollectionTypeProjectNumberParamsWithTimeout(timeout time.Duration) *GetCollectionTypeProjectNumberParams {
	return &GetCollectionTypeProjectNumberParams{
		timeout: timeout,
	}
}

// NewGetCollectionTypeProjectNumberParamsWithContext creates a new GetCollectionTypeProjectNumberParams object
// with the ability to set a context for a request.
func NewGetCollectionTypeProjectNumberParamsWithContext(ctx context.Context) *GetCollectionTypeProjectNumberParams {
	return &GetCollectionTypeProjectNumberParams{
		Context: ctx,
	}
}

// NewGetCollectionTypeProjectNumberParamsWithHTTPClient creates a new GetCollectionTypeProjectNumberParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollectionTypeProjectNumberParamsWithHTTPClient(client *http.Client) *GetCollectionTypeProjectNumberParams {
	return &GetCollectionTypeProjectNumberParams{
		HTTPClient: client,
	}
}

/*
GetCollectionTypeProjectNumberParams contains all the parameters to send to the API endpoint

	for the get collection type project number operation.

	Typically these are written to a http.Request.
*/
type GetCollectionTypeProjectNumberParams struct {

	/* Number.

	   project number
	*/
	Number string

	/* Type.

	   type of collection
	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get collection type project number params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionTypeProjectNumberParams) WithDefaults() *GetCollectionTypeProjectNumberParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get collection type project number params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionTypeProjectNumberParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) WithTimeout(timeout time.Duration) *GetCollectionTypeProjectNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) WithContext(ctx context.Context) *GetCollectionTypeProjectNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) WithHTTPClient(client *http.Client) *GetCollectionTypeProjectNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNumber adds the number to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) WithNumber(number string) *GetCollectionTypeProjectNumberParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) SetNumber(number string) {
	o.Number = number
}

// WithType adds the typeVar to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) WithType(typeVar string) *GetCollectionTypeProjectNumberParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get collection type project number params
func (o *GetCollectionTypeProjectNumberParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionTypeProjectNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param number
	if err := r.SetPathParam("number", o.Number); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
