// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/client/models"
)

// PostJobReader is a Reader for the PostJob structure.
type PostJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostJobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /job] PostJob", response, response.Code())
	}
}

// NewPostJobOK creates a PostJobOK with default headers values
func NewPostJobOK() *PostJobOK {
	return &PostJobOK{}
}

/*
PostJobOK describes a response with status code 200, with default header values.

success
*/
type PostJobOK struct {
	Payload *models.JobInfo
}

// IsSuccess returns true when this post job o k response has a 2xx status code
func (o *PostJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post job o k response has a 3xx status code
func (o *PostJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post job o k response has a 4xx status code
func (o *PostJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post job o k response has a 5xx status code
func (o *PostJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post job o k response a status code equal to that given
func (o *PostJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post job o k response
func (o *PostJobOK) Code() int {
	return 200
}

func (o *PostJobOK) Error() string {
	return fmt.Sprintf("[POST /job][%d] postJobOK  %+v", 200, o.Payload)
}

func (o *PostJobOK) String() string {
	return fmt.Sprintf("[POST /job][%d] postJobOK  %+v", 200, o.Payload)
}

func (o *PostJobOK) GetPayload() *models.JobInfo {
	return o.Payload
}

func (o *PostJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostJobInternalServerError creates a PostJobInternalServerError with default headers values
func NewPostJobInternalServerError() *PostJobInternalServerError {
	return &PostJobInternalServerError{}
}

/*
PostJobInternalServerError describes a response with status code 500, with default header values.

failure
*/
type PostJobInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this post job internal server error response has a 2xx status code
func (o *PostJobInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post job internal server error response has a 3xx status code
func (o *PostJobInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post job internal server error response has a 4xx status code
func (o *PostJobInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post job internal server error response has a 5xx status code
func (o *PostJobInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post job internal server error response a status code equal to that given
func (o *PostJobInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post job internal server error response
func (o *PostJobInternalServerError) Code() int {
	return 500
}

func (o *PostJobInternalServerError) Error() string {
	return fmt.Sprintf("[POST /job][%d] postJobInternalServerError  %+v", 500, o.Payload)
}

func (o *PostJobInternalServerError) String() string {
	return fmt.Sprintf("[POST /job][%d] postJobInternalServerError  %+v", 500, o.Payload)
}

func (o *PostJobInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *PostJobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
