// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/client/models"
)

// PostJobsReader is a Reader for the PostJobs structure.
type PostJobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostJobsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostJobsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 207:
		result := NewPostJobsMultiStatus()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostJobsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /jobs] PostJobs", response, response.Code())
	}
}

// NewPostJobsOK creates a PostJobsOK with default headers values
func NewPostJobsOK() *PostJobsOK {
	return &PostJobsOK{}
}

/*
PostJobsOK describes a response with status code 200, with default header values.

success
*/
type PostJobsOK struct {
	Payload *models.ResponseBodyJobs
}

// IsSuccess returns true when this post jobs o k response has a 2xx status code
func (o *PostJobsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post jobs o k response has a 3xx status code
func (o *PostJobsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post jobs o k response has a 4xx status code
func (o *PostJobsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post jobs o k response has a 5xx status code
func (o *PostJobsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post jobs o k response a status code equal to that given
func (o *PostJobsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post jobs o k response
func (o *PostJobsOK) Code() int {
	return 200
}

func (o *PostJobsOK) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsOK  %+v", 200, o.Payload)
}

func (o *PostJobsOK) String() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsOK  %+v", 200, o.Payload)
}

func (o *PostJobsOK) GetPayload() *models.ResponseBodyJobs {
	return o.Payload
}

func (o *PostJobsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyJobs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostJobsMultiStatus creates a PostJobsMultiStatus with default headers values
func NewPostJobsMultiStatus() *PostJobsMultiStatus {
	return &PostJobsMultiStatus{}
}

/*
PostJobsMultiStatus describes a response with status code 207, with default header values.

multi-status
*/
type PostJobsMultiStatus struct {
	Payload *models.ResponseBodyJobs
}

// IsSuccess returns true when this post jobs multi status response has a 2xx status code
func (o *PostJobsMultiStatus) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post jobs multi status response has a 3xx status code
func (o *PostJobsMultiStatus) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post jobs multi status response has a 4xx status code
func (o *PostJobsMultiStatus) IsClientError() bool {
	return false
}

// IsServerError returns true when this post jobs multi status response has a 5xx status code
func (o *PostJobsMultiStatus) IsServerError() bool {
	return false
}

// IsCode returns true when this post jobs multi status response a status code equal to that given
func (o *PostJobsMultiStatus) IsCode(code int) bool {
	return code == 207
}

// Code gets the status code for the post jobs multi status response
func (o *PostJobsMultiStatus) Code() int {
	return 207
}

func (o *PostJobsMultiStatus) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsMultiStatus  %+v", 207, o.Payload)
}

func (o *PostJobsMultiStatus) String() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsMultiStatus  %+v", 207, o.Payload)
}

func (o *PostJobsMultiStatus) GetPayload() *models.ResponseBodyJobs {
	return o.Payload
}

func (o *PostJobsMultiStatus) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyJobs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostJobsInternalServerError creates a PostJobsInternalServerError with default headers values
func NewPostJobsInternalServerError() *PostJobsInternalServerError {
	return &PostJobsInternalServerError{}
}

/*
PostJobsInternalServerError describes a response with status code 500, with default header values.

failure
*/
type PostJobsInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this post jobs internal server error response has a 2xx status code
func (o *PostJobsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post jobs internal server error response has a 3xx status code
func (o *PostJobsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post jobs internal server error response has a 4xx status code
func (o *PostJobsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post jobs internal server error response has a 5xx status code
func (o *PostJobsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post jobs internal server error response a status code equal to that given
func (o *PostJobsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post jobs internal server error response
func (o *PostJobsInternalServerError) Code() int {
	return 500
}

func (o *PostJobsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostJobsInternalServerError) String() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostJobsInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *PostJobsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
