// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/client/models"
)

// NewPostJobsParams creates a new PostJobsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostJobsParams() *PostJobsParams {
	return &PostJobsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostJobsParamsWithTimeout creates a new PostJobsParams object
// with the ability to set a timeout on a request.
func NewPostJobsParamsWithTimeout(timeout time.Duration) *PostJobsParams {
	return &PostJobsParams{
		timeout: timeout,
	}
}

// NewPostJobsParamsWithContext creates a new PostJobsParams object
// with the ability to set a context for a request.
func NewPostJobsParamsWithContext(ctx context.Context) *PostJobsParams {
	return &PostJobsParams{
		Context: ctx,
	}
}

// NewPostJobsParamsWithHTTPClient creates a new PostJobsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostJobsParamsWithHTTPClient(client *http.Client) *PostJobsParams {
	return &PostJobsParams{
		HTTPClient: client,
	}
}

/*
PostJobsParams contains all the parameters to send to the API endpoint

	for the post jobs operation.

	Typically these are written to a http.Request.
*/
type PostJobsParams struct {

	/* Data.

	   stager job data
	*/
	Data *models.RequestBodyJobs

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostJobsParams) WithDefaults() *PostJobsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostJobsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post jobs params
func (o *PostJobsParams) WithTimeout(timeout time.Duration) *PostJobsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post jobs params
func (o *PostJobsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post jobs params
func (o *PostJobsParams) WithContext(ctx context.Context) *PostJobsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post jobs params
func (o *PostJobsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post jobs params
func (o *PostJobsParams) WithHTTPClient(client *http.Client) *PostJobsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post jobs params
func (o *PostJobsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post jobs params
func (o *PostJobsParams) WithData(data *models.RequestBodyJobs) *PostJobsParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post jobs params
func (o *PostJobsParams) SetData(data *models.RequestBodyJobs) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PostJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
