// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/client/models"
)

// PutJobScheduledIDReader is a Reader for the PutJobScheduledID structure.
type PutJobScheduledIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutJobScheduledIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutJobScheduledIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutJobScheduledIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutJobScheduledIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutJobScheduledIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /job/scheduled/{id}] PutJobScheduledID", response, response.Code())
	}
}

// NewPutJobScheduledIDOK creates a PutJobScheduledIDOK with default headers values
func NewPutJobScheduledIDOK() *PutJobScheduledIDOK {
	return &PutJobScheduledIDOK{}
}

/*
PutJobScheduledIDOK describes a response with status code 200, with default header values.

success
*/
type PutJobScheduledIDOK struct {
	Payload *models.JobInfo
}

// IsSuccess returns true when this put job scheduled Id o k response has a 2xx status code
func (o *PutJobScheduledIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put job scheduled Id o k response has a 3xx status code
func (o *PutJobScheduledIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put job scheduled Id o k response has a 4xx status code
func (o *PutJobScheduledIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put job scheduled Id o k response has a 5xx status code
func (o *PutJobScheduledIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put job scheduled Id o k response a status code equal to that given
func (o *PutJobScheduledIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put job scheduled Id o k response
func (o *PutJobScheduledIDOK) Code() int {
	return 200
}

func (o *PutJobScheduledIDOK) Error() string {
	return fmt.Sprintf("[PUT /job/scheduled/{id}][%d] putJobScheduledIdOK  %+v", 200, o.Payload)
}

func (o *PutJobScheduledIDOK) String() string {
	return fmt.Sprintf("[PUT /job/scheduled/{id}][%d] putJobScheduledIdOK  %+v", 200, o.Payload)
}

func (o *PutJobScheduledIDOK) GetPayload() *models.JobInfo {
	return o.Payload
}

func (o *PutJobScheduledIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutJobScheduledIDBadRequest creates a PutJobScheduledIDBadRequest with default headers values
func NewPutJobScheduledIDBadRequest() *PutJobScheduledIDBadRequest {
	return &PutJobScheduledIDBadRequest{}
}

/*
PutJobScheduledIDBadRequest describes a response with status code 400, with default header values.

bad request
*/
type PutJobScheduledIDBadRequest struct {
	Payload string
}

// IsSuccess returns true when this put job scheduled Id bad request response has a 2xx status code
func (o *PutJobScheduledIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put job scheduled Id bad request response has a 3xx status code
func (o *PutJobScheduledIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put job scheduled Id bad request response has a 4xx status code
func (o *PutJobScheduledIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put job scheduled Id bad request response has a 5xx status code
func (o *PutJobScheduledIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put job scheduled Id bad request response a status code equal to that given
func (o *PutJobScheduledIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put job scheduled Id bad request response
func (o *PutJobScheduledIDBadRequest) Code() int {
	return 400
}

func (o *PutJobScheduledIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /job/scheduled/{id}][%d] putJobScheduledIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutJobScheduledIDBadRequest) String() string {
	return fmt.Sprintf("[PUT /job/scheduled/{id}][%d] putJobScheduledIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutJobScheduledIDBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PutJobScheduledIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutJobScheduledIDNotFound creates a PutJobScheduledIDNotFound with default headers values
func NewPutJobScheduledIDNotFound() *PutJobScheduledIDNotFound {
	return &PutJobScheduledIDNotFound{}
}

/*
PutJobScheduledIDNotFound describes a response with status code 404, with default header values.

job not found
*/
type PutJobScheduledIDNotFound struct {
	Payload string
}

// IsSuccess returns true when this put job scheduled Id not found response has a 2xx status code
func (o *PutJobScheduledIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put job scheduled Id not found response has a 3xx status code
func (o *PutJobScheduledIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put job scheduled Id not found response has a 4xx status code
func (o *PutJobScheduledIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put job scheduled Id not found response has a 5xx status code
func (o *PutJobScheduledIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put job scheduled Id not found response a status code equal to that given
func (o *PutJobScheduledIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put job scheduled Id not found response
func (o *PutJobScheduledIDNotFound) Code() int {
	return 404
}

func (o *PutJobScheduledIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /job/scheduled/{id}][%d] putJobScheduledIdNotFound  %+v", 404, o.Payload)
}

func (o *PutJobScheduledIDNotFound) String() string {
	return fmt.Sprintf("[PUT /job/scheduled/{id}][%d] putJobScheduledIdNotFound  %+v", 404, o.Payload)
}

func (o *PutJobScheduledIDNotFound) GetPayload() string {
	return o.Payload
}

func (o *PutJobScheduledIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutJobScheduledIDInternalServerError creates a PutJobScheduledIDInternalServerError with default headers values
func NewPutJobScheduledIDInternalServerError() *PutJobScheduledIDInternalServerError {
	return &PutJobScheduledIDInternalServerError{}
}

/*
PutJobScheduledIDInternalServerError describes a response with status code 500, with default header values.

failure
*/
type PutJobScheduledIDInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this put job scheduled Id internal server error response has a 2xx status code
func (o *PutJobScheduledIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put job scheduled Id internal server error response has a 3xx status code
func (o *PutJobScheduledIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put job scheduled Id internal server error response has a 4xx status code
func (o *PutJobScheduledIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put job scheduled Id internal server error response has a 5xx status code
func (o *PutJobScheduledIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put job scheduled Id internal server error response a status code equal to that given
func (o *PutJobScheduledIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put job scheduled Id internal server error response
func (o *PutJobScheduledIDInternalServerError) Code() int {
	return 500
}

func (o *PutJobScheduledIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /job/scheduled/{id}][%d] putJobScheduledIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutJobScheduledIDInternalServerError) String() string {
	return fmt.Sprintf("[PUT /job/scheduled/{id}][%d] putJobScheduledIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutJobScheduledIDInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *PutJobScheduledIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
