// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/server/models"
)

// GetDirOKCode is the HTTP code returned for type GetDirOK
const GetDirOKCode int = 200

/*
GetDirOK success

swagger:response getDirOK
*/
type GetDirOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseDirEntries `json:"body,omitempty"`
}

// NewGetDirOK creates GetDirOK with default headers values
func NewGetDirOK() *GetDirOK {

	return &GetDirOK{}
}

// WithPayload adds the payload to the get dir o k response
func (o *GetDirOK) WithPayload(payload *models.ResponseDirEntries) *GetDirOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dir o k response
func (o *GetDirOK) SetPayload(payload *models.ResponseDirEntries) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDirInternalServerErrorCode is the HTTP code returned for type GetDirInternalServerError
const GetDirInternalServerErrorCode int = 500

/*
GetDirInternalServerError failure

swagger:response getDirInternalServerError
*/
type GetDirInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetDirInternalServerError creates GetDirInternalServerError with default headers values
func NewGetDirInternalServerError() *GetDirInternalServerError {

	return &GetDirInternalServerError{}
}

// WithPayload adds the payload to the get dir internal server error response
func (o *GetDirInternalServerError) WithPayload(payload *models.ResponseBody500) *GetDirInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dir internal server error response
func (o *GetDirInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
