// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/server/models"
)

// GetCollectionTypeProjectNumberOKCode is the HTTP code returned for type GetCollectionTypeProjectNumberOK
const GetCollectionTypeProjectNumberOKCode int = 200

/*
GetCollectionTypeProjectNumberOK success

swagger:response getCollectionTypeProjectNumberOK
*/
type GetCollectionTypeProjectNumberOK struct {

	/*
	  In: Body
	*/
	Payload *models.Collection `json:"body,omitempty"`
}

// NewGetCollectionTypeProjectNumberOK creates GetCollectionTypeProjectNumberOK with default headers values
func NewGetCollectionTypeProjectNumberOK() *GetCollectionTypeProjectNumberOK {

	return &GetCollectionTypeProjectNumberOK{}
}

// WithPayload adds the payload to the get collection type project number o k response
func (o *GetCollectionTypeProjectNumberOK) WithPayload(payload *models.Collection) *GetCollectionTypeProjectNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collection type project number o k response
func (o *GetCollectionTypeProjectNumberOK) SetPayload(payload *models.Collection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionTypeProjectNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCollectionTypeProjectNumberNotFoundCode is the HTTP code returned for type GetCollectionTypeProjectNumberNotFound
const GetCollectionTypeProjectNumberNotFoundCode int = 404

/*
GetCollectionTypeProjectNumberNotFound collection not found

swagger:response getCollectionTypeProjectNumberNotFound
*/
type GetCollectionTypeProjectNumberNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetCollectionTypeProjectNumberNotFound creates GetCollectionTypeProjectNumberNotFound with default headers values
func NewGetCollectionTypeProjectNumberNotFound() *GetCollectionTypeProjectNumberNotFound {

	return &GetCollectionTypeProjectNumberNotFound{}
}

// WithPayload adds the payload to the get collection type project number not found response
func (o *GetCollectionTypeProjectNumberNotFound) WithPayload(payload string) *GetCollectionTypeProjectNumberNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collection type project number not found response
func (o *GetCollectionTypeProjectNumberNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionTypeProjectNumberNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCollectionTypeProjectNumberInternalServerErrorCode is the HTTP code returned for type GetCollectionTypeProjectNumberInternalServerError
const GetCollectionTypeProjectNumberInternalServerErrorCode int = 500

/*
GetCollectionTypeProjectNumberInternalServerError failure

swagger:response getCollectionTypeProjectNumberInternalServerError
*/
type GetCollectionTypeProjectNumberInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetCollectionTypeProjectNumberInternalServerError creates GetCollectionTypeProjectNumberInternalServerError with default headers values
func NewGetCollectionTypeProjectNumberInternalServerError() *GetCollectionTypeProjectNumberInternalServerError {

	return &GetCollectionTypeProjectNumberInternalServerError{}
}

// WithPayload adds the payload to the get collection type project number internal server error response
func (o *GetCollectionTypeProjectNumberInternalServerError) WithPayload(payload *models.ResponseBody500) *GetCollectionTypeProjectNumberInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collection type project number internal server error response
func (o *GetCollectionTypeProjectNumberInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionTypeProjectNumberInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
