// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/server/models"
)

// GetJobsOKCode is the HTTP code returned for type GetJobsOK
const GetJobsOKCode int = 200

/*
GetJobsOK success

swagger:response getJobsOK
*/
type GetJobsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyJobs `json:"body,omitempty"`
}

// NewGetJobsOK creates GetJobsOK with default headers values
func NewGetJobsOK() *GetJobsOK {

	return &GetJobsOK{}
}

// WithPayload adds the payload to the get jobs o k response
func (o *GetJobsOK) WithPayload(payload *models.ResponseBodyJobs) *GetJobsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get jobs o k response
func (o *GetJobsOK) SetPayload(payload *models.ResponseBodyJobs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetJobsInternalServerErrorCode is the HTTP code returned for type GetJobsInternalServerError
const GetJobsInternalServerErrorCode int = 500

/*
GetJobsInternalServerError failure

swagger:response getJobsInternalServerError
*/
type GetJobsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetJobsInternalServerError creates GetJobsInternalServerError with default headers values
func NewGetJobsInternalServerError() *GetJobsInternalServerError {

	return &GetJobsInternalServerError{}
}

// WithPayload adds the payload to the get jobs internal server error response
func (o *GetJobsInternalServerError) WithPayload(payload *models.ResponseBody500) *GetJobsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get jobs internal server error response
func (o *GetJobsInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
