// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/server/models"
)

// GetJobsStatusOKCode is the HTTP code returned for type GetJobsStatusOK
const GetJobsStatusOKCode int = 200

/*GetJobsStatusOK success

swagger:response getJobsStatusOK
*/
type GetJobsStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyJobs `json:"body,omitempty"`
}

// NewGetJobsStatusOK creates GetJobsStatusOK with default headers values
func NewGetJobsStatusOK() *GetJobsStatusOK {

	return &GetJobsStatusOK{}
}

// WithPayload adds the payload to the get jobs status o k response
func (o *GetJobsStatusOK) WithPayload(payload *models.ResponseBodyJobs) *GetJobsStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get jobs status o k response
func (o *GetJobsStatusOK) SetPayload(payload *models.ResponseBodyJobs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobsStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetJobsStatusBadRequestCode is the HTTP code returned for type GetJobsStatusBadRequest
const GetJobsStatusBadRequestCode int = 400

/*GetJobsStatusBadRequest bad request

swagger:response getJobsStatusBadRequest
*/
type GetJobsStatusBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody400 `json:"body,omitempty"`
}

// NewGetJobsStatusBadRequest creates GetJobsStatusBadRequest with default headers values
func NewGetJobsStatusBadRequest() *GetJobsStatusBadRequest {

	return &GetJobsStatusBadRequest{}
}

// WithPayload adds the payload to the get jobs status bad request response
func (o *GetJobsStatusBadRequest) WithPayload(payload *models.ResponseBody400) *GetJobsStatusBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get jobs status bad request response
func (o *GetJobsStatusBadRequest) SetPayload(payload *models.ResponseBody400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobsStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetJobsStatusInternalServerErrorCode is the HTTP code returned for type GetJobsStatusInternalServerError
const GetJobsStatusInternalServerErrorCode int = 500

/*GetJobsStatusInternalServerError failure

swagger:response getJobsStatusInternalServerError
*/
type GetJobsStatusInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetJobsStatusInternalServerError creates GetJobsStatusInternalServerError with default headers values
func NewGetJobsStatusInternalServerError() *GetJobsStatusInternalServerError {

	return &GetJobsStatusInternalServerError{}
}

// WithPayload adds the payload to the get jobs status internal server error response
func (o *GetJobsStatusInternalServerError) WithPayload(payload *models.ResponseBody500) *GetJobsStatusInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get jobs status internal server error response
func (o *GetJobsStatusInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobsStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
