// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetCollectionTypeProjectNumberParams creates a new GetCollectionTypeProjectNumberParams object
//
// There are no default values defined in the spec.
func NewGetCollectionTypeProjectNumberParams() GetCollectionTypeProjectNumberParams {

	return GetCollectionTypeProjectNumberParams{}
}

// GetCollectionTypeProjectNumberParams contains all the bound params for the get collection type project number operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCollectionTypeProjectNumber
type GetCollectionTypeProjectNumberParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*project number
	  Required: true
	  In: path
	*/
	Number string
	/*type of collection
	  Required: true
	  In: path
	*/
	Type string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCollectionTypeProjectNumberParams() beforehand.
func (o *GetCollectionTypeProjectNumberParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rNumber, rhkNumber, _ := route.Params.GetOK("number")
	if err := o.bindNumber(rNumber, rhkNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	rType, rhkType, _ := route.Params.GetOK("type")
	if err := o.bindType(rType, rhkType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindNumber binds and validates parameter Number from path.
func (o *GetCollectionTypeProjectNumberParams) bindNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Number = raw

	return nil
}

// bindType binds and validates parameter Type from path.
func (o *GetCollectionTypeProjectNumberParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Type = raw

	if err := o.validateType(formats); err != nil {
		return err
	}

	return nil
}

// validateType carries on validations for parameter Type
func (o *GetCollectionTypeProjectNumberParams) validateType(formats strfmt.Registry) error {

	if err := validate.EnumCase("type", "path", o.Type, []interface{}{"dac", "DAC", "rdc", "RDC", "dsc", "DSC"}, true); err != nil {
		return err
	}

	return nil
}
