// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/server/models"
)

// GetJobsStatusHandlerFunc turns a function with the right signature into a get jobs status handler
type GetJobsStatusHandlerFunc func(GetJobsStatusParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetJobsStatusHandlerFunc) Handle(params GetJobsStatusParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetJobsStatusHandler interface for that can handle valid get jobs status params
type GetJobsStatusHandler interface {
	Handle(GetJobsStatusParams, *models.Principal) middleware.Responder
}

// NewGetJobsStatus creates a new http.Handler for the get jobs status operation
func NewGetJobsStatus(ctx *middleware.Context, handler GetJobsStatusHandler) *GetJobsStatus {
	return &GetJobsStatus{Context: ctx, Handler: handler}
}

/*
	GetJobsStatus swagger:route GET /jobs/{status} getJobsStatus

get list of jobs at given status
*/
type GetJobsStatus struct {
	Context *middleware.Context
	Handler GetJobsStatusHandler
}

func (o *GetJobsStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetJobsStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
