// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/server/models"
)

// PostJobOKCode is the HTTP code returned for type PostJobOK
const PostJobOKCode int = 200

/*
PostJobOK success

swagger:response postJobOK
*/
type PostJobOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyJobInfo `json:"body,omitempty"`
}

// NewPostJobOK creates PostJobOK with default headers values
func NewPostJobOK() *PostJobOK {

	return &PostJobOK{}
}

// WithPayload adds the payload to the post job o k response
func (o *PostJobOK) WithPayload(payload *models.ResponseBodyJobInfo) *PostJobOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post job o k response
func (o *PostJobOK) SetPayload(payload *models.ResponseBodyJobInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostJobOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostJobInternalServerErrorCode is the HTTP code returned for type PostJobInternalServerError
const PostJobInternalServerErrorCode int = 500

/*
PostJobInternalServerError failure

swagger:response postJobInternalServerError
*/
type PostJobInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewPostJobInternalServerError creates PostJobInternalServerError with default headers values
func NewPostJobInternalServerError() *PostJobInternalServerError {

	return &PostJobInternalServerError{}
}

// WithPayload adds the payload to the post job internal server error response
func (o *PostJobInternalServerError) WithPayload(payload *models.ResponseBody500) *PostJobInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post job internal server error response
func (o *PostJobInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostJobInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
