// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/server/models"
)

// PostJobsOKCode is the HTTP code returned for type PostJobsOK
const PostJobsOKCode int = 200

/*
PostJobsOK success

swagger:response postJobsOK
*/
type PostJobsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyJobs `json:"body,omitempty"`
}

// NewPostJobsOK creates PostJobsOK with default headers values
func NewPostJobsOK() *PostJobsOK {

	return &PostJobsOK{}
}

// WithPayload adds the payload to the post jobs o k response
func (o *PostJobsOK) WithPayload(payload *models.ResponseBodyJobs) *PostJobsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post jobs o k response
func (o *PostJobsOK) SetPayload(payload *models.ResponseBodyJobs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostJobsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostJobsMultiStatusCode is the HTTP code returned for type PostJobsMultiStatus
const PostJobsMultiStatusCode int = 207

/*
PostJobsMultiStatus multi-status

swagger:response postJobsMultiStatus
*/
type PostJobsMultiStatus struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyJobs `json:"body,omitempty"`
}

// NewPostJobsMultiStatus creates PostJobsMultiStatus with default headers values
func NewPostJobsMultiStatus() *PostJobsMultiStatus {

	return &PostJobsMultiStatus{}
}

// WithPayload adds the payload to the post jobs multi status response
func (o *PostJobsMultiStatus) WithPayload(payload *models.ResponseBodyJobs) *PostJobsMultiStatus {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post jobs multi status response
func (o *PostJobsMultiStatus) SetPayload(payload *models.ResponseBodyJobs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostJobsMultiStatus) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(207)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostJobsInternalServerErrorCode is the HTTP code returned for type PostJobsInternalServerError
const PostJobsInternalServerErrorCode int = 500

/*
PostJobsInternalServerError failure

swagger:response postJobsInternalServerError
*/
type PostJobsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewPostJobsInternalServerError creates PostJobsInternalServerError with default headers values
func NewPostJobsInternalServerError() *PostJobsInternalServerError {

	return &PostJobsInternalServerError{}
}

// WithPayload adds the payload to the post jobs internal server error response
func (o *PostJobsInternalServerError) WithPayload(payload *models.ResponseBody500) *PostJobsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post jobs internal server error response
func (o *PostJobsInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostJobsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
