// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/dccn-tg/dr-data-stager/pkg/swagger/server/models"
)

// PostJobsHandlerFunc turns a function with the right signature into a post jobs handler
type PostJobsHandlerFunc func(PostJobsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostJobsHandlerFunc) Handle(params PostJobsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostJobsHandler interface for that can handle valid post jobs params
type PostJobsHandler interface {
	Handle(PostJobsParams, *models.Principal) middleware.Responder
}

// NewPostJobs creates a new http.Handler for the post jobs operation
func NewPostJobs(ctx *middleware.Context, handler PostJobsHandler) *PostJobs {
	return &PostJobs{Context: ctx, Handler: handler}
}

/*
	PostJobs swagger:route POST /jobs postJobs

create multiple new stager jobs
*/
type PostJobs struct {
	Context *middleware.Context
	Handler PostJobsHandler
}

func (o *PostJobs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostJobsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
