// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/server/models"
)

// PutJobScheduledIDOKCode is the HTTP code returned for type PutJobScheduledIDOK
const PutJobScheduledIDOKCode int = 200

/*
PutJobScheduledIDOK success

swagger:response putJobScheduledIdOK
*/
type PutJobScheduledIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.JobInfo `json:"body,omitempty"`
}

// NewPutJobScheduledIDOK creates PutJobScheduledIDOK with default headers values
func NewPutJobScheduledIDOK() *PutJobScheduledIDOK {

	return &PutJobScheduledIDOK{}
}

// WithPayload adds the payload to the put job scheduled Id o k response
func (o *PutJobScheduledIDOK) WithPayload(payload *models.JobInfo) *PutJobScheduledIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put job scheduled Id o k response
func (o *PutJobScheduledIDOK) SetPayload(payload *models.JobInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutJobScheduledIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutJobScheduledIDBadRequestCode is the HTTP code returned for type PutJobScheduledIDBadRequest
const PutJobScheduledIDBadRequestCode int = 400

/*
PutJobScheduledIDBadRequest bad request

swagger:response putJobScheduledIdBadRequest
*/
type PutJobScheduledIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutJobScheduledIDBadRequest creates PutJobScheduledIDBadRequest with default headers values
func NewPutJobScheduledIDBadRequest() *PutJobScheduledIDBadRequest {

	return &PutJobScheduledIDBadRequest{}
}

// WithPayload adds the payload to the put job scheduled Id bad request response
func (o *PutJobScheduledIDBadRequest) WithPayload(payload string) *PutJobScheduledIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put job scheduled Id bad request response
func (o *PutJobScheduledIDBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutJobScheduledIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutJobScheduledIDNotFoundCode is the HTTP code returned for type PutJobScheduledIDNotFound
const PutJobScheduledIDNotFoundCode int = 404

/*
PutJobScheduledIDNotFound job not found

swagger:response putJobScheduledIdNotFound
*/
type PutJobScheduledIDNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutJobScheduledIDNotFound creates PutJobScheduledIDNotFound with default headers values
func NewPutJobScheduledIDNotFound() *PutJobScheduledIDNotFound {

	return &PutJobScheduledIDNotFound{}
}

// WithPayload adds the payload to the put job scheduled Id not found response
func (o *PutJobScheduledIDNotFound) WithPayload(payload string) *PutJobScheduledIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put job scheduled Id not found response
func (o *PutJobScheduledIDNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutJobScheduledIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutJobScheduledIDInternalServerErrorCode is the HTTP code returned for type PutJobScheduledIDInternalServerError
const PutJobScheduledIDInternalServerErrorCode int = 500

/*
PutJobScheduledIDInternalServerError failure

swagger:response putJobScheduledIdInternalServerError
*/
type PutJobScheduledIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewPutJobScheduledIDInternalServerError creates PutJobScheduledIDInternalServerError with default headers values
func NewPutJobScheduledIDInternalServerError() *PutJobScheduledIDInternalServerError {

	return &PutJobScheduledIDInternalServerError{}
}

// WithPayload adds the payload to the put job scheduled Id internal server error response
func (o *PutJobScheduledIDInternalServerError) WithPayload(payload *models.ResponseBody500) *PutJobScheduledIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put job scheduled Id internal server error response
func (o *PutJobScheduledIDInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutJobScheduledIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
