// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/Donders-Institute/dr-data-stager/pkg/swagger/server/models"
)

// PutJobScheduledIDHandlerFunc turns a function with the right signature into a put job scheduled ID handler
type PutJobScheduledIDHandlerFunc func(PutJobScheduledIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutJobScheduledIDHandlerFunc) Handle(params PutJobScheduledIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutJobScheduledIDHandler interface for that can handle valid put job scheduled ID params
type PutJobScheduledIDHandler interface {
	Handle(PutJobScheduledIDParams, *models.Principal) middleware.Responder
}

// NewPutJobScheduledID creates a new http.Handler for the put job scheduled ID operation
func NewPutJobScheduledID(ctx *middleware.Context, handler PutJobScheduledIDHandler) *PutJobScheduledID {
	return &PutJobScheduledID{Context: ctx, Handler: handler}
}

/*
	PutJobScheduledID swagger:route PUT /job/scheduled/{id} putJobScheduledId

reschedule a job in completed or archived state
*/
type PutJobScheduledID struct {
	Context *middleware.Context
	Handler PutJobScheduledIDHandler
}

func (o *PutJobScheduledID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutJobScheduledIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
