swagger: "2.0"

basePath: /v1

info:
  description: Donders Repository data stager APIs
  title: dr-data-stager
  version: 0.1.0

securityDefinitions:
  basicAuth:
    type: basic
  oauth2:
    type: oauth2
    flow: application
    tokenUrl: 'https://login.dccn.nl/connect/token'
    scopes:
      urn:dccn:data-stager-api:*: general access scope for data-stager API server

# API paths
paths:

  /ping:
    get:
      summary: check API server health
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: success
          schema:
            type: string
            enum: [pong]
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'

  /jobs:
    post:
      summary: create multiple new stager jobs
      security:
        - oauth2: [urn:dccn:data-stager-api:*]
        - basicAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          description: stager job data
          name: data
          schema:
            $ref: '#/definitions/requestBodyJobs'
          required: true
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/responseBodyJobs'
        207:
          description: multi-status
          schema:
            $ref: '#/definitions/responseBodyJobs'
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'
    get:
      summary: get all jobs of a user
      security:
        - oauth2: [urn:dccn:data-stager-api:*]
        - basicAuth: []
      consumes:
        - application/json
      produces:
        - application/json      
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/responseBodyJobs'
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'

  /jobs/{status}:
    get:
      summary: get list of jobs at given status
      security:
        - oauth2: [urn:dccn:data-stager-api:*]
        - basicAuth: []
      consumes:
        - application/json
      produces:
        - application/json      
      parameters:
        - in: path
          name: status
          description: job status
          type: string
          enum: [waiting, processing, failed, succeeded, canceled]
          required: true
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/responseBodyJobs'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/responseBody400'
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'

  /job:
    post:
      summary: create a new stager job
      security:
        - oauth2: [urn:dccn:data-stager-api:*]
        - basicAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: data
          description: stager job data
          required: true
          schema:
            $ref: '#/definitions/jobData'
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/jobInfo'
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'

  /job/{id}:
    get:
      summary: get stager job information
      security:
        - oauth2: [urn:dccn:data-stager-api:*]
        - basicAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: job identifier
          type: string
          required: true
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/jobInfo'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/responseBody400'
        404:
          description: job not found
          schema:
            type: string
            enum: [job not found]
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'
    delete:
      summary: cancel a stager job
      security:
        - oauth2: [urn:dccn:data-stager-api:*]
        - basicAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: job identifier
          type: string
          required: true
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/jobInfo'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/responseBody400'
        404:
          description: job not found
          schema:
            type: string
            enum: [job not found]
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'

  /dir:
    get:
      summary: get entities within a filesystem path
      security:
        - oauth2: [urn:dccn:data-stager-api:*]
        - basicAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: dir
          description: the directory
          required: true
          schema:
            $ref: '#/definitions/dirPath'
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/responseDirEntries'
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'

  /dac/project/{number}:
    get:
      summary: retrieve the Data Acquisition Collection associated with a project 
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: number
          description: project number
          type: string
          required: true
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/collection'
        404:
          description: collection not found
          schema:
            type: string
            enum: [collection not found]
        500:
          description: failure
          schema:
            $ref: '#/definitions/responseBody500'

# object definitions
definitions:

  requestBodyJobs:
    description: JSON object containing a list of job data.
    properties:
      jobs:
        type: array
        items:
          $ref: '#/definitions/jobData'

  responseBody400:
    description: JSON object containing error message concerning bad client request.
    properties:
      errorMessage:
        description: error message specifying the bad request.
        type: string

  responseBody500:
    description: JSON object containing server side error.
    properties:
      exitCode:
        description: server-side exit code.
        type: integer
      errorMessage:
        description: server-side error message.
        type: string

  collection:
    description: JSON object of a RDR collection
    properties:
      collName:
        description: iRODS namespace for the collection
        type: string
    required:
      - collName

  jobInfo:
    description: JSON object containing scheduled job information.
    properties:
      id:
        $ref: '#/definitions/jobID'
      timestamps:
        $ref: '#/definitions/jobTimestamps'
      data:
        $ref: '#/definitions/jobData'
      status:
        $ref: '#/definitions/jobStatus'
    required:
      - id
      - data
      - timestamps
      - status

  jobTimestamps:
    description: job timestamps
    properties:
      createdAt:
        description: timestamp at which the job is created.
        type: integer
      lastFailedAt:
        description: timestamp at which the job failed the last time, -62135596800 (0001-01-01T00:00:00) if not applicable.
        type: integer
      nextProcessAt:
        description: timestamp at which the job will be processed, -62135596800 (0001-01-01T00:00:00) if not applicable.
        type: integer
      completedAt:
        description: timestamp at which the job is completed, -62135596800 (0001-01-01T00:00:00) if not applicable.
        type: integer
    required:
      - createdAt
      - lastFailedAt
      - nextProcessAt
      - completedAt

  responseDirEntries:
    description: JSON object containing dir entries.
    properties:
      entries:
        type: array
        items:
          $ref: '#/definitions/dirEntry'

  dirPath:
    description: directory path data
    properties:
      path:
        description: path of the directory
        type: string
    required:
      - path

  dirEntry:
    description: directory entry
    properties:
      name:
        description: name of the entry
        type: string
      type:
        description: type of the entry
        type: string
        enum: [regular, dir, symlink, unknown]
      size:
        description: size of the entry in bytes
        type: integer
    required:
      - name
      - type
      - size

  responseBodyJobs:
    description: JSON object containing a list of job information.
    properties:
      jobs:
        type: array
        items:
          $ref: '#/definitions/jobInfo'

  jobData:
    description: job data
    properties:
      title:
        description: short description about the job
        type: string
      stagerUser:
        description: username of the stager user
        type: string
      stagerUserEmail:
        description: email of the stager user
        type: string
        format: email
      drUser:
        description: username of the DR data-access account
        type: string
      drPass:
        description: password of the DR data-access account
        type: string
      srcURL:
        description: path or DR namespace (prefixed with irods:) of the source endpoint
        type: string
      dstURL:
        description: path or DR namespace (prefixed with irods:) of the destination endpoint
        type: string
      timeout:
        description: allowed duration in seconds for entire transfer job (0 for no timeout)
        type: integer
      timeout_noprogress:
        description: allowed duration in seconds for no further transfer progress (0 for no timeout)
        type: integer
    required:
      - title
      - stagerUser
      - drUser
      - srcURL
      - dstURL

  jobID:
    description: identifier for scheduled background tasks.
    type: string

  jobStatus:
    description: status of the background task.
    properties:
      status:
        description: job status from the last execution.
        type: string
        enum: [waiting, processing, failed, succeeded, canceled]
      error:
        description: job error message from the last execution.
        type: string
      attempts:
        description: number of attempts
        type: integer
      progress:
        description: job progress info from the last execution.
        $ref: '#/definitions/jobProgress'
    required:
      - status
      - error
      - attempts
      - progress

  jobProgress:
    description: job progress information
    properties:
      total:
        description: number of total files to be processed
        type: integer
      processed:
        description: number of processed files
        type: integer
      failed:
        description: number of failed files
        type: integer
    required:
      - total
      - processed
      - failed

  principal:
    description: authenticated client identifier
    type: string
