dr:
  irodsHost: icat.localhost
  irodsPort: 1247
  irodsZone: nl.ru.donders
  irodsAuthScheme: native
  irodsSslCacert: /opt/irods/ssl/icat.pem
  irodsSslKeysize: 32
  irodsSslAlgorithm: AES-256-CBC
  irodsSslSaltSize: 8
  irodsHashRounds: 16
  organisationalUnits:
    - name: DCCN
      irodsUser: user
      irodsPass: pass
    - name: DCC
      irodsUser: user
      irodsPass: pass
mailer:
  host: localhost
  port: 25
  auth_plain_user: user
  auth_plain_pass: pass
admins:
  - admin1@
  - admin2@