// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JobProgress job progress information
//
// swagger:model jobProgress
type JobProgress struct {

	// number of failed files
	// Required: true
	Failed *int64 `json:"failed"`

	// number of processed files
	// Required: true
	Processed *int64 `json:"processed"`

	// number of total files to be processed
	// Required: true
	Total *int64 `json:"total"`
}

// Validate validates this job progress
func (m *JobProgress) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFailed(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProcessed(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotal(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobProgress) validateFailed(formats strfmt.Registry) error {

	if err := validate.Required("failed", "body", m.Failed); err != nil {
		return err
	}

	return nil
}

func (m *JobProgress) validateProcessed(formats strfmt.Registry) error {

	if err := validate.Required("processed", "body", m.Processed); err != nil {
		return err
	}

	return nil
}

func (m *JobProgress) validateTotal(formats strfmt.Registry) error {

	if err := validate.Required("total", "body", m.Total); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this job progress based on context it is used
func (m *JobProgress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobProgress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobProgress) UnmarshalBinary(b []byte) error {
	var res JobProgress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
